version: "3.8"

services:
  db:
    image: postgres:15
    container_name: piscine_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mservage
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - ./database:/var/lib/postgresql/data